In [115]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import seaborn as sns 
import datetime


from sklearn.preprocessing import OneHotEncoder


In [228]:
mass = pd.read_pickle('./data/02b_added_prosperity.pickle') 

In [229]:
mass.head()

id country  ccode  year         region  protestnumber  startday  \
0  201990001  Canada     20  1990  North America              1      15.0   
1  201990002  Canada     20  1990  North America              2      25.0   
2  201990003  Canada     20  1990  North America              3       1.0   
3  201990004  Canada     20  1990  North America              4      12.0   
4  201990005  Canada     20  1990  North America              5      14.0   

   startmonth  startyear  endday  ...  \
0         1.0     1990.0    15.0  ...   
1         6.0     1990.0    25.0  ...   
2         7.0     1990.0     1.0  ...   
3         7.0     1990.0     6.0  ...   
4         8.0     1990.0    15.0  ...   

                                             sources  \
0  1. great canadian train journeys into history;...   
1  1. autonomy s cry revived in quebec the new yo...   
2  1. quebec protest after queen calls for unity ...   
3  1. indians gather as siege intensifies; armed ...   
4  1. dozens hurt in mohawk blockade protest the ...   

                                               notes  protester_id_type  \
0  canada s railway passenger system was finally ...     workers_unions   
1  protestors were only identified as young peopl...     students_youth   
2  the queen, after calling on canadians to remai...    political_group   
3  canada s federal government has agreed to acqu...       ethnic_group   
4  protests were directed against the state due t...   locals_residents   

  partipants_number protest_size_category    PopMale  PopFemale   PopTotal  \
0              1000           1,000-4,999  13656.649  13884.674  27541.323   
1              1000           1,000-4,999  13656.649  13884.674  27541.323   
2               500               100-999  13656.649  13884.674  27541.323   
3               100               100-999  13656.649  13884.674  27541.323   
4               950               100-999  13656.649  13884.674  27541.323   

  PopDensity prosperity_2020  
0      3.029       79.819703  
1      3.029       79.819703  
2      3.029       79.819703  
3      3.029       79.819703  
4      3.029       79.819703  

[5 rows x 36 columns]

In [230]:
mass.shape

(15225, 36)

In [231]:
mass.columns

Index(['id', 'country', 'ccode', 'year', 'region', 'protestnumber', 'startday',
       'startmonth', 'startyear', 'endday', 'endmonth', 'endyear',
       'protesterviolence', 'location', 'protesteridentity',
       'protesterdemand1', 'protesterdemand2', 'protesterdemand3',
       'protesterdemand4', 'stateresponse1', 'stateresponse2',
       'stateresponse3', 'stateresponse4', 'stateresponse5', 'stateresponse6',
       'stateresponse7', 'sources', 'notes', 'protester_id_type',
       'partipants_number', 'protest_size_category', 'PopMale', 'PopFemale',
       'PopTotal', 'PopDensity', 'prosperity_2020'],
      dtype='object')

In [232]:
# Clean up column names 
mass.rename(columns = {'PopMale':'pop_male', 'PopFemale':'pop_female', 'PopTotal':'pop_total', 'PopDensity':'pop_density'}, inplace = True) 

### OneHotEncode country, region, stateresponses & protesterdemands columns

In [233]:
# df with categorical variables that we want to encode
df = mass[['country', 'region','protesterdemand1', 'protesterdemand2', 'protesterdemand3',
       'protesterdemand4', 'stateresponse1', 'stateresponse2',
       'stateresponse3', 'stateresponse4', 'stateresponse5', 'stateresponse6',
       'stateresponse7', 'protest_size_category', 'protester_id_type']]
df.head()

country         region             protesterdemand1    protesterdemand2  \
0  Canada  North America  political behavior, process  labor wage dispute   
1  Canada  North America  political behavior, process                 NaN   
2  Canada  North America  political behavior, process                 NaN   
3  Canada  North America              land farm issue                 NaN   
4  Canada  North America  political behavior, process                 NaN   

  protesterdemand3 protesterdemand4   stateresponse1 stateresponse2  \
0              NaN              NaN           ignore            NaN   
1              NaN              NaN           ignore            NaN   
2              NaN              NaN           ignore            NaN   
3              NaN              NaN     accomodation            NaN   
4              NaN              NaN  crowd dispersal        arrests   

  stateresponse3 stateresponse4 stateresponse5 stateresponse6 stateresponse7  \
0            NaN            NaN            NaN            NaN            NaN   
1            NaN            NaN            NaN            NaN            NaN   
2            NaN            NaN            NaN            NaN            NaN   
3            NaN            NaN            NaN            NaN            NaN   
4   accomodation            NaN            NaN            NaN            NaN   

  protest_size_category protester_id_type  
0           1,000-4,999    workers_unions  
1           1,000-4,999    students_youth  
2               100-999   political_group  
3               100-999      ethnic_group  
4               100-999  locals_residents

In [234]:
df.isnull().sum()

country                      0
region                       0
protesterdemand1             1
protesterdemand2         12251
protesterdemand3         14842
protesterdemand4         14446
stateresponse1              31
stateresponse2           12341
stateresponse3           14296
stateresponse4           14982
stateresponse5           14428
stateresponse6           15209
stateresponse7           14369
protest_size_category        0
protester_id_type            0
dtype: int64

In [235]:
# fill null values with 'None'
df.fillna('None', inplace=True)
df.isnull().sum()

C:\Users\tsuts\anaconda3\lib\site-packages\pandas\core\frame.py:4317: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(


country                  0
region                   0
protesterdemand1         0
protesterdemand2         0
protesterdemand3         0
protesterdemand4         0
stateresponse1           0
stateresponse2           0
stateresponse3           0
stateresponse4           0
stateresponse5           0
stateresponse6           0
stateresponse7           0
protest_size_category    0
protester_id_type        0
dtype: int64

In [236]:
# one hot encode stateresponses
onehot = OneHotEncoder(dtype=np.int, sparse=True)

ohe_df = pd.DataFrame(onehot.fit_transform(df[['country', 'region','stateresponse1', 'stateresponse2', 'stateresponse3', 'stateresponse4',
       'stateresponse5', 'stateresponse6', 'stateresponse7', 'protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4', 'protest_size_category', 'protester_id_type']]).toarray(),
                         columns=onehot.get_feature_names(['country', 'region','stateresponse1', 'stateresponse2', 'stateresponse3', 'stateresponse4',
       'stateresponse5', 'stateresponse6', 'stateresponse7', 'protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4', 'protest_size_category', 'protester_id_type']))

In [237]:
ohe_df.columns

Index(['country_Afghanistan', 'country_Albania', 'country_Algeria',
       'country_Angola', 'country_Argentina', 'country_Armenia',
       'country_Austria', 'country_Azerbaijan', 'country_Bahrain',
       'country_Bangladesh',
       ...
       'protester_id_type_pensioners_retirees',
       'protester_id_type_political_group', 'protester_id_type_prisoners',
       'protester_id_type_protestors_generic',
       'protester_id_type_religious_group',
       'protester_id_type_soldiers_veterans',
       'protester_id_type_students_youth',
       'protester_id_type_victims_families', 'protester_id_type_women',
       'protester_id_type_workers_unions'],
      dtype='object', length=276)

In [238]:
ohe_df.head()

country_Afghanistan  country_Albania  country_Algeria  country_Angola  \
0                    0                0                0               0   
1                    0                0                0               0   
2                    0                0                0               0   
3                    0                0                0               0   
4                    0                0                0               0   

   country_Argentina  country_Armenia  country_Austria  country_Azerbaijan  \
0                  0                0                0                   0   
1                  0                0                0                   0   
2                  0                0                0                   0   
3                  0                0                0                   0   
4                  0                0                0                   0   

   country_Bahrain  country_Bangladesh  ...  \
0                0                   0  ...   
1                0                   0  ...   
2                0                   0  ...   
3                0                   0  ...   
4                0                   0  ...   

   protester_id_type_pensioners_retirees  protester_id_type_political_group  \
0                                      0                                  0   
1                                      0                                  0   
2                                      0                                  1   
3                                      0                                  0   
4                                      0                                  0   

   protester_id_type_prisoners  protester_id_type_protestors_generic  \
0                            0                                     0   
1                            0                                     0   
2                            0                                     0   
3                            0                                     0   
4                            0                                     0   

   protester_id_type_religious_group  protester_id_type_soldiers_veterans  \
0                                  0                                    0   
1                                  0                                    0   
2                                  0                                    0   
3                                  0                                    0   
4                                  0                                    0   

   protester_id_type_students_youth  protester_id_type_victims_families  \
0                                 0                                   0   
1                                 1                                   0   
2                                 0                                   0   
3                                 0                                   0   
4                                 0                                   0   

   protester_id_type_women  protester_id_type_workers_unions  
0                        0                                 1  
1                        0                                 0  
2                        0                                 0  
3                        0                                 0  
4                        0                                 0  

[5 rows x 276 columns]

## Clean the Encoded dataframe

In [239]:
# we want to consolidate each response/demand into their own columns 
# rather than having multiple government response/protester demand columns
ohe_df['arrests'] = ohe_df['stateresponse1_arrests'] + ohe_df['stateresponse2_arrests'] + ohe_df['stateresponse3_arrests'] + ohe_df['stateresponse4_arrests'] + ohe_df['stateresponse5_arrests'] + ohe_df['stateresponse6_arrests'] + ohe_df['stateresponse7_arrests'] 
ohe_df['accomodation'] = ohe_df['stateresponse1_accomodation'] + ohe_df['stateresponse2_accomodation'] + ohe_df['stateresponse3_accomodation'] + ohe_df['stateresponse4_accomodation'] + ohe_df['stateresponse5_accomodation'] + ohe_df['stateresponse6_accomodation'] + ohe_df['stateresponse7_accomodation'] 
ohe_df['beatings'] = ohe_df['stateresponse1_beatings'] + ohe_df['stateresponse2_beatings'] + ohe_df['stateresponse3_beatings'] + ohe_df['stateresponse4_beatings'] + ohe_df['stateresponse5_beatings'] + ohe_df['stateresponse6_beatings'] + ohe_df['stateresponse7_beatings'] 
ohe_df['crowddispersal'] = ohe_df['stateresponse1_crowd dispersal'] + ohe_df['stateresponse2_crowd dispersal'] + ohe_df['stateresponse3_crowd dispersal'] + ohe_df['stateresponse4_crowd dispersal'] + ohe_df['stateresponse5_crowd dispersal'] + ohe_df['stateresponse6_crowd dispersal'] 
ohe_df['ignore'] = ohe_df['stateresponse1_ignore'] + ohe_df['stateresponse2_ignore'] + ohe_df['stateresponse3_ignore']
ohe_df['killings'] = ohe_df['stateresponse1_killings'] + ohe_df['stateresponse2_killings'] + ohe_df['stateresponse3_killings'] + ohe_df['stateresponse4_killings'] + ohe_df['stateresponse5_killings'] + ohe_df['stateresponse6_killings'] + ohe_df['stateresponse7_killings'] 
ohe_df['no_response'] = ohe_df['stateresponse1_None'] + ohe_df['stateresponse2_None'] + ohe_df['stateresponse3_None'] + ohe_df['stateresponse4_None'] + ohe_df['stateresponse5_None'] + ohe_df['stateresponse6_None'] + ohe_df['stateresponse7_None'] 
ohe_df['shootings'] = ohe_df['stateresponse1_shootings'] + ohe_df['stateresponse2_shootings'] + ohe_df['stateresponse3_shootings'] + ohe_df['stateresponse4_shootings'] + ohe_df['stateresponse5_shootings'] 

ohe_df['labor_wage_dispute'] = ohe_df['protesterdemand1_labor wage dispute'] + ohe_df['protesterdemand2_labor wage dispute'] + ohe_df['protesterdemand3_labor wage dispute'] + ohe_df['protesterdemand4_labor wage dispute'] 
ohe_df['land_farm_issue'] = ohe_df['protesterdemand1_land farm issue'] + ohe_df['protesterdemand2_land farm issue'] + ohe_df['protesterdemand3_land farm issue'] + ohe_df['protesterdemand4_land farm issue'] 
ohe_df['no_demands'] = ohe_df['protesterdemand1_None'] + ohe_df['protesterdemand2_None'] + ohe_df['protesterdemand3_None'] + ohe_df['protesterdemand4_None'] 
ohe_df['police_brutality'] = ohe_df['protesterdemand1_police brutality'] + ohe_df['protesterdemand2_police brutality'] + ohe_df['protesterdemand3_police brutality'] + ohe_df['protesterdemand4_police brutality'] 
ohe_df['political_behavior_process'] = ohe_df['protesterdemand1_political behavior, process'] + ohe_df['protesterdemand2_political behavior, process'] + ohe_df['protesterdemand3_political behavior, process'] + ohe_df['protesterdemand4_political behavior, process'] 
ohe_df['price increases_tax_policy'] = ohe_df['protesterdemand1_price increases, tax policy'] + ohe_df['protesterdemand2_price increases, tax policy'] + ohe_df['protesterdemand3_price increases, tax policy'] + ohe_df['protesterdemand4_price increases, tax policy']
ohe_df['removal_of_politician'] = ohe_df['protesterdemand1_removal of politician'] + ohe_df['protesterdemand2_removal of politician'] + ohe_df['protesterdemand3_removal of politician'] + ohe_df['protesterdemand4_removal of politician']
ohe_df['social_restrictions'] = ohe_df['protesterdemand1_social restrictions'] + ohe_df['protesterdemand2_social restrictions'] + ohe_df['protesterdemand3_social restrictions']
ohe_df.head()

country_Afghanistan  country_Albania  country_Algeria  country_Angola  \
0                    0                0                0               0   
1                    0                0                0               0   
2                    0                0                0               0   
3                    0                0                0               0   
4                    0                0                0               0   

   country_Argentina  country_Armenia  country_Austria  country_Azerbaijan  \
0                  0                0                0                   0   
1                  0                0                0                   0   
2                  0                0                0                   0   
3                  0                0                0                   0   
4                  0                0                0                   0   

   country_Bahrain  country_Bangladesh  ...  no_response  shootings  \
0                0                   0  ...            6          0   
1                0                   0  ...            6          0   
2                0                   0  ...            6          0   
3                0                   0  ...            6          0   
4                0                   0  ...            4          0   

   labor_wage_dispute  land_farm_issue  no_demands  police_brutality  \
0                   1                0           2                 0   
1                   0                0           3                 0   
2                   0                0           3                 0   
3                   0                1           3                 0   
4                   0                0           3                 0   

   political_behavior_process  price increases_tax_policy  \
0                           1                           0   
1                           1                           0   
2                           1                           0   
3                           0                           0   
4                           1                           0   

   removal_of_politician  social_restrictions  
0                      0                    0  
1                      0                    0  
2                      0                    0  
3                      0                    0  
4                      0                    0  

[5 rows x 292 columns]

In [240]:
# turn no_response and no_demands column values to 0 or 1
ohe_df['no_response'] = ohe_df['no_response'].map(lambda b: 1 if b > 0 else 0)
ohe_df['no_demands'] = ohe_df['no_demands'].map(lambda b: 1 if b > 0 else 0)

print(ohe_df['no_demands'].unique()) 
print(ohe_df['no_response'].unique())

[1 0]
[1 0]


In [241]:
# clean response columns to (0,1)

ohe_df['arrests'] = ohe_df['arrests'].map(lambda x: 1 if x >= 1 else 0)
ohe_df['accomodation'] = ohe_df['accomodation'].map(lambda x: 1 if x >= 1 else 0)
ohe_df['beatings'] = ohe_df['beatings'].map(lambda x: 1 if x >= 1 else 0)
ohe_df['crowddispersal'] = ohe_df['crowddispersal'].map(lambda x: 1 if x >= 1 else 0)
ohe_df['ignore'] = ohe_df['ignore'].map(lambda x: 1 if x >= 1 else 0)
ohe_df['killings'] = ohe_df['killings'].map(lambda x: 1 if x >= 1 else 0)
ohe_df['no_response'] = ohe_df['no_response'].map(lambda x: 1 if x >= 1 else 0)
ohe_df['shootings'] = ohe_df['shootings'].map(lambda x: 1 if x >= 1 else 0)

ohe_df.head()

country_Afghanistan  country_Albania  country_Algeria  country_Angola  \
0                    0                0                0               0   
1                    0                0                0               0   
2                    0                0                0               0   
3                    0                0                0               0   
4                    0                0                0               0   

   country_Argentina  country_Armenia  country_Austria  country_Azerbaijan  \
0                  0                0                0                   0   
1                  0                0                0                   0   
2                  0                0                0                   0   
3                  0                0                0                   0   
4                  0                0                0                   0   

   country_Bahrain  country_Bangladesh  ...  no_response  shootings  \
0                0                   0  ...            1          0   
1                0                   0  ...            1          0   
2                0                   0  ...            1          0   
3                0                   0  ...            1          0   
4                0                   0  ...            1          0   

   labor_wage_dispute  land_farm_issue  no_demands  police_brutality  \
0                   1                0           1                 0   
1                   0                0           1                 0   
2                   0                0           1                 0   
3                   0                1           1                 0   
4                   0                0           1                 0   

   political_behavior_process  price increases_tax_policy  \
0                           1                           0   
1                           1                           0   
2                           1                           0   
3                           0                           0   
4                           1                           0   

   removal_of_politician  social_restrictions  
0                      0                    0  
1                      0                    0  
2                      0                    0  
3                      0                    0  
4                      0                    0  

[5 rows x 292 columns]

In [242]:
# same thing for demand columns that have values that are greater than 1
ohe_df['price increases_tax_policy'] = ohe_df['price increases_tax_policy'].map(lambda x: 1 if x >= 1 else 0)
ohe_df['removal_of_politician'] = ohe_df['removal_of_politician'].map(lambda x: 1 if x >= 1 else 0)


In [266]:
ohe_df.columns

Index(['country_Afghanistan', 'country_Albania', 'country_Algeria',
       'country_Angola', 'country_Argentina', 'country_Armenia',
       'country_Austria', 'country_Azerbaijan', 'country_Bahrain',
       'country_Bangladesh',
       ...
       'ignore', 'killings', 'shootings', 'labor_wage_dispute',
       'land_farm_issue', 'police_brutality', 'political_behavior_process',
       'price increases_tax_policy', 'removal_of_politician',
       'social_restrictions'],
      dtype='object', length=207)

In [244]:
# we don't need any of these columns 
ohe_df.drop(columns=['no_response', 'no_demands','protesterdemand1_labor wage dispute',
       'protesterdemand1_land farm issue', 'protesterdemand1_None',
       'protesterdemand1_police brutality',
       'protesterdemand1_political behavior, process',
       'protesterdemand1_price increases, tax policy',
       'protesterdemand1_removal of politician',
       'protesterdemand1_social restrictions',
       'protesterdemand2_labor wage dispute',
       'protesterdemand2_land farm issue', 'protesterdemand2_None',
       'protesterdemand2_police brutality',
       'protesterdemand2_political behavior, process',
       'protesterdemand2_price increases, tax policy',
       'protesterdemand2_removal of politician',
       'protesterdemand2_social restrictions',
       'protesterdemand3_labor wage dispute',
       'protesterdemand3_land farm issue', 'protesterdemand3_None',
       'protesterdemand3_police brutality',
       'protesterdemand3_political behavior, process',
       'protesterdemand3_price increases, tax policy',
       'protesterdemand3_removal of politician',
       'protesterdemand3_social restrictions', 'protesterdemand4_.',
       'protesterdemand4_labor wage dispute',
       'protesterdemand4_land farm issue', 'protesterdemand4_None',
       'protesterdemand4_police brutality',
       'protesterdemand4_political behavior, process',
       'protesterdemand4_price increases, tax policy',
       'protesterdemand4_removal of politician','stateresponse1_accomodation', 'stateresponse1_arrests',
       'stateresponse1_beatings', 'stateresponse1_crowd dispersal',
       'stateresponse1_ignore', 'stateresponse1_killings',
       'stateresponse1_None', 'stateresponse1_shootings',
       'stateresponse2_accomodation', 'stateresponse2_arrests',
       'stateresponse2_beatings', 'stateresponse2_crowd dispersal',
       'stateresponse2_ignore', 'stateresponse2_killings',
       'stateresponse2_None', 'stateresponse2_shootings',
       'stateresponse3_accomodation', 'stateresponse3_arrests',
       'stateresponse3_beatings', 'stateresponse3_crowd dispersal',
       'stateresponse3_ignore', 'stateresponse3_killings',
       'stateresponse3_None', 'stateresponse3_shootings',
       'stateresponse4_accomodation', 'stateresponse4_arrests',
       'stateresponse4_beatings', 'stateresponse4_crowd dispersal',
       'stateresponse4_killings', 'stateresponse4_None',
       'stateresponse4_shootings', 'stateresponse5_.',
       'stateresponse5_accomodation', 'stateresponse5_arrests',
       'stateresponse5_beatings', 'stateresponse5_crowd dispersal',
       'stateresponse5_killings', 'stateresponse5_None',
       'stateresponse5_shootings', 'stateresponse6_accomodation',
       'stateresponse6_arrests', 'stateresponse6_beatings',
       'stateresponse6_crowd dispersal', 'stateresponse6_killings',
       'stateresponse6_None', 'stateresponse7_.',
       'stateresponse7_accomodation', 'stateresponse7_arrests',
       'stateresponse7_beatings', 'stateresponse7_killings',
       'stateresponse7_None'], inplace=True)
ohe_df.shape

(15225, 207)

In [245]:
# concat protest_demands and state_reponses

mass = pd.concat([mass,ohe_df], axis=1, join='inner')
mass.head()

id country  ccode  year         region  protestnumber  startday  \
0  201990001  Canada     20  1990  North America              1      15.0   
1  201990002  Canada     20  1990  North America              2      25.0   
2  201990003  Canada     20  1990  North America              3       1.0   
3  201990004  Canada     20  1990  North America              4      12.0   
4  201990005  Canada     20  1990  North America              5      14.0   

   startmonth  startyear  endday  ...  ignore  killings  shootings  \
0         1.0     1990.0    15.0  ...       1         0          0   
1         6.0     1990.0    25.0  ...       1         0          0   
2         7.0     1990.0     1.0  ...       1         0          0   
3         7.0     1990.0     6.0  ...       0         0          0   
4         8.0     1990.0    15.0  ...       0         0          0   

  labor_wage_dispute land_farm_issue police_brutality  \
0                  1               0                0   
1                  0               0                0   
2                  0               0                0   
3                  0               1                0   
4                  0               0                0   

  political_behavior_process price increases_tax_policy removal_of_politician  \
0                          1                          0                     0   
1                          1                          0                     0   
2                          1                          0                     0   
3                          0                          0                     0   
4                          1                          0                     0   

  social_restrictions  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  

[5 rows x 243 columns]

In [250]:
mass.columns[200:243]

Index(['country_Zimbabwe', 'region_Africa', 'region_Asia',
       'region_Central America', 'region_Europe', 'region_MENA',
       'region_North America', 'region_Oceania', 'region_South America',
       'protest_size_category_1,000-4,999',
       'protest_size_category_10,000-100,000', 'protest_size_category_100-999',
       'protest_size_category_5,000-9,999', 'protest_size_category_50-99',
       'protest_size_category_Less than 50',
       'protest_size_category_Over 100,000',
       'protester_id_type_civil_human_rights',
       'protester_id_type_ethnic_group', 'protester_id_type_locals_residents',
       'protester_id_type_pensioners_retirees',
       'protester_id_type_political_group', 'protester_id_type_prisoners',
       'protester_id_type_protestors_generic',
       'protester_id_type_religious_group',
       'protester_id_type_soldiers_veterans',
       'protester_id_type_students_youth',
       'protester_id_type_victims_families', 'protester_id_type_women',
       'prote

In [252]:
mass.shape

(15225, 243)

## Create datetime column

In [253]:
mass['startday'].head()

0    15.0
1    25.0
2     1.0
3    12.0
4    14.0
Name: startday, dtype: float64

In [254]:
mass['startmonth'].head()

0    1.0
1    6.0
2    7.0
3    7.0
4    8.0
Name: startmonth, dtype: float64

In [255]:
mass[['day', 'month', 'year']] = mass[['startday', 'startmonth', 'startyear']].astype(int)
mass['start_date'] = pd.to_datetime(mass[['year', 'month', 'day']])
mass['start_date'].head()

0   1990-01-15
1   1990-06-25
2   1990-07-01
3   1990-07-12
4   1990-08-14
Name: start_date, dtype: datetime64[ns]

In [256]:
mass[['day', 'month', 'year']] = mass[['endday', 'endmonth', 'endyear']].astype(int)
mass['end_date'] = pd.to_datetime(mass[['year', 'month', 'day']])
mass['end_date']

0       1990-01-15
1       1990-06-25
2       1990-07-01
3       1990-09-06
4       1990-08-15
           ...    
15220   2014-02-18
15221   2016-06-09
15222   2017-06-15
15223   2017-07-15
15224   2017-10-31
Name: end_date, Length: 15225, dtype: datetime64[ns]

In [257]:
mass.head()

id country  ccode  year         region  protestnumber  startday  \
0  201990001  Canada     20  1990  North America              1      15.0   
1  201990002  Canada     20  1990  North America              2      25.0   
2  201990003  Canada     20  1990  North America              3       1.0   
3  201990004  Canada     20  1990  North America              4      12.0   
4  201990005  Canada     20  1990  North America              5      14.0   

   startmonth  startyear  endday  ...  land_farm_issue  police_brutality  \
0         1.0     1990.0    15.0  ...                0                 0   
1         6.0     1990.0    25.0  ...                0                 0   
2         7.0     1990.0     1.0  ...                0                 0   
3         7.0     1990.0     6.0  ...                1                 0   
4         8.0     1990.0    15.0  ...                0                 0   

   political_behavior_process price increases_tax_policy  \
0                           1                          0   
1                           1                          0   
2                           1                          0   
3                           0                          0   
4                           1                          0   

  removal_of_politician social_restrictions day month start_date   end_date  
0                     0                   0  15     1 1990-01-15 1990-01-15  
1                     0                   0  25     6 1990-06-25 1990-06-25  
2                     0                   0   1     7 1990-07-01 1990-07-01  
3                     0                   0   6     9 1990-07-12 1990-09-06  
4                     0                   0  15     8 1990-08-14 1990-08-15  

[5 rows x 247 columns]

In [258]:
# we don't need these columns 
mass.drop(columns=['day', 'month', 'year', 'startday', 'startmonth', 'startyear', 'endday', 'endmonth', 'endyear', 
                   'protesterdemand1','protesterdemand2', 'protesterdemand3', 'protesterdemand4',
                    'stateresponse1', 'stateresponse2', 'stateresponse3', 'stateresponse4',
                   'stateresponse5', 'stateresponse6', 'stateresponse7'], inplace=True)
mass.isnull().sum().head(50)

id                                   0
country                              0
ccode                                0
region                               0
protestnumber                        0
protesterviolence                    0
location                            21
protesteridentity                    0
sources                              4
notes                               46
protester_id_type                    0
partipants_number                    0
protest_size_category                0
pop_male                             0
pop_female                           0
pop_total                            0
pop_density                          0
prosperity_2020                      0
country_Afghanistan                  0
country_Albania                      0
country_Algeria                      0
country_Angola                       0
country_Argentina                    0
country_Armenia                      0
country_Austria                      0
country_Azerbaijan       

In [259]:
mass.isnull().sum().head(50)

id                                   0
country                              0
ccode                                0
region                               0
protestnumber                        0
protesterviolence                    0
location                            21
protesteridentity                    0
sources                              4
notes                               46
protester_id_type                    0
partipants_number                    0
protest_size_category                0
pop_male                             0
pop_female                           0
pop_total                            0
pop_density                          0
prosperity_2020                      0
country_Afghanistan                  0
country_Albania                      0
country_Algeria                      0
country_Angola                       0
country_Argentina                    0
country_Armenia                      0
country_Austria                      0
country_Azerbaijan       

- we're going to get rid of null values in our notes column when we do a sentiment analysis on it 
- we are not going to use the other columns with null values


In [261]:
mass.head()

id country  ccode         region  protestnumber  protesterviolence  \
0  201990001  Canada     20  North America              1                0.0   
1  201990002  Canada     20  North America              2                0.0   
2  201990003  Canada     20  North America              3                0.0   
3  201990004  Canada     20  North America              4                1.0   
4  201990005  Canada     20  North America              5                1.0   

           location           protesteridentity  \
0          national                 unspecified   
1  Montreal, Quebec                 unspecified   
2  Montreal, Quebec  separatist parti quebecois   
3  Montreal, Quebec              mohawk indians   
4  Montreal, Quebec             local residents   

                                             sources  \
0  1. great canadian train journeys into history;...   
1  1. autonomy s cry revived in quebec the new yo...   
2  1. quebec protest after queen calls for unity ...   
3  1. indians gather as siege intensifies; armed ...   
4  1. dozens hurt in mohawk blockade protest the ...   

                                               notes  ... shootings  \
0  canada s railway passenger system was finally ...  ...         0   
1  protestors were only identified as young peopl...  ...         0   
2  the queen, after calling on canadians to remai...  ...         0   
3  canada s federal government has agreed to acqu...  ...         0   
4  protests were directed against the state due t...  ...         0   

   labor_wage_dispute land_farm_issue  police_brutality  \
0                   1               0                 0   
1                   0               0                 0   
2                   0               0                 0   
3                   0               1                 0   
4                   0               0                 0   

   political_behavior_process  price increases_tax_policy  \
0                           1                           0   
1                           1                           0   
2                           1                           0   
3                           0                           0   
4                           1                           0   

   removal_of_politician  social_restrictions  start_date   end_date  
0                      0                    0  1990-01-15 1990-01-15  
1                      0                    0  1990-06-25 1990-06-25  
2                      0                    0  1990-07-01 1990-07-01  
3                      0                    0  1990-07-12 1990-09-06  
4                      0                    0  1990-08-14 1990-08-15  

[5 rows x 227 columns]

## Create target column with array of government responses for NeuralNetwork

In [262]:
target = []
for i in np.array((mass[['arrests', 'accomodation', 'beatings',
       'crowddispersal', 'ignore', 'killings', 'shootings']])): 
    print(i)
    target.append(i)
target

[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[1 1 0 1 0 0 0]
[0 0 0 1 0 0 1]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 1 1]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[1 0 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 0 1 1 0 0 0]
[1 0 0 1 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0

[0 0 0 0 0 1 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 1 0 1 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1

[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[1 0 0 1 0 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[1 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[1 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0

[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 1 1 1 1 0 0]
[0 1 0 1 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 1 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 1 0 1 1 0 0]
[0 0 0 1 0 0 0]
[0 1 0 0 0 0 0]
[1 1 0 1 0 0 0]
[1 1 1 1 0 0 0]
[1 1 1 1 0 0 0]
[0 1 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 1 0 1 1 0 0]
[0 1 0 0 1 0 0]
[0 1 0 0 1 0 0]
[0 1 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0

[0 0 0 0 1 0 0]
[0 0 0 1 0 1 1]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 1]
[0 1 0 0 0 0 0]
[1 0 0 1 0 0 1]
[0 0 0 0 1 0 0]
[0 1 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 1 0 1 0 0 0]
[0 1 1 1 0 0 0]
[0 1 0 1 0 0 0]
[0 1 0 0 1 0 0]
[0 0 0 1 0 0 1]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 0 1 1]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 1 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 1 1 0 0 0]
[0 0 1 1 0 0 0]
[0 0 0 1 0 0 0]
[1 0 0 1 0 0 0]
[1 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[1 0 0 1 0 0 0]
[0 0 1 1 0 0 1]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1

[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 1 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 1 0 0 0 0]
[0 0 0 1 0 0 1]
[0 0 1 1 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 0 0 1 0 1 1]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 1]
[0 0 1 0 0 0 0]
[1 0 1 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 1 1 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 1 1 0 1 1]
[0 0 0 1 0 0 1]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 1 1 0 0 0]
[0 1 0 0 1 0 0]
[0 0 1 1 0 0 0]
[0 0 1 0 0 0 0]
[0 1 0 1

[0 1 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[0 1 0 0 1 0 0]
[0 1 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 0 1]
[1 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 1 0 0 0 0 1]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 1 0]
[0 1 1 0 0 0 0]
[0 0 0 1 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 1 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 1 0 0 0]
[0 0 1 0 0 0 0]
[0 0 0 1 0 0 0]
[1 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 1 0 0 1 0 0]
[0 1 1 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 0 0 1]
[0 0 0 1 0 0 0]
[0 0 0 0 0 0 1]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 0 1]
[0 0 0 0 0 1 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[1 0 0 0

[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 1 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 1 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0

[array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([1, 1, 0, 1, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 1, 0, 0, 1], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([1, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([1, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 1, 1], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([0, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dtype=int64),
 array([1, 0, 0, 1, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 0], dt

In [263]:
mass['target'] = [list(target[i]) for i in range(len(target))]
mass['target']

0        [0, 0, 0, 0, 1, 0, 0]
1        [0, 0, 0, 0, 1, 0, 0]
2        [0, 0, 0, 0, 1, 0, 0]
3        [0, 1, 0, 0, 0, 0, 0]
4        [1, 1, 0, 1, 0, 0, 0]
                 ...          
15220    [0, 0, 0, 1, 0, 0, 1]
15221    [0, 0, 0, 1, 0, 1, 1]
15222    [0, 1, 0, 0, 0, 0, 0]
15223    [0, 0, 0, 1, 0, 0, 0]
15224    [0, 0, 0, 0, 1, 0, 0]
Name: target, Length: 15225, dtype: object

In [264]:
mass.head(6)

id country  ccode         region  protestnumber  protesterviolence  \
0  201990001  Canada     20  North America              1                0.0   
1  201990002  Canada     20  North America              2                0.0   
2  201990003  Canada     20  North America              3                0.0   
3  201990004  Canada     20  North America              4                1.0   
4  201990005  Canada     20  North America              5                1.0   
5  201990006  Canada     20  North America              6                0.0   

                                      location           protesteridentity  \
0                                     national                 unspecified   
1                             Montreal, Quebec                 unspecified   
2                             Montreal, Quebec  separatist parti quebecois   
3                             Montreal, Quebec              mohawk indians   
4                             Montreal, Quebec             local residents   
5  Kahnawake Reservation near Montreal, Quebec              mohawk indians   

                                             sources  \
0  1. great canadian train journeys into history;...   
1  1. autonomy s cry revived in quebec the new yo...   
2  1. quebec protest after queen calls for unity ...   
3  1. indians gather as siege intensifies; armed ...   
4  1. dozens hurt in mohawk blockade protest the ...   
5  1. mohawks tear gassed in clash the washington...   

                                               notes  ... labor_wage_dispute  \
0  canada s railway passenger system was finally ...  ...                  1   
1  protestors were only identified as young peopl...  ...                  0   
2  the queen, after calling on canadians to remai...  ...                  0   
3  canada s federal government has agreed to acqu...  ...                  0   
4  protests were directed against the state due t...  ...                  0   
5  canadian army troops today fired tear gas into...  ...                  0   

   land_farm_issue police_brutality  political_behavior_process  \
0                0                0                           1   
1                0                0                           1   
2                0                0                           1   
3                1                0                           0   
4                0                0                           1   
5                0                1                           0   

   price increases_tax_policy  removal_of_politician  social_restrictions  \
0                           0                      0                    0   
1                           0                      0                    0   
2                           0                      0                    0   
3                           0                      0                    0   
4                           0                      0                    0   
5                           0                      0                    0   

   start_date   end_date                 target  
0  1990-01-15 1990-01-15  [0, 0, 0, 0, 1, 0, 0]  
1  1990-06-25 1990-06-25  [0, 0, 0, 0, 1, 0, 0]  
2  1990-07-01 1990-07-01  [0, 0, 0, 0, 1, 0, 0]  
3  1990-07-12 1990-09-06  [0, 1, 0, 0, 0, 0, 0]  
4  1990-08-14 1990-08-15  [1, 1, 0, 1, 0, 0, 0]  
5  1990-09-19 1990-09-19  [0, 0, 0, 1, 0, 0, 1]  

[6 rows x 228 columns]

In [265]:
# Save to pickle file 
mass.to_pickle('./data/04_dummy_df.pickle')